### ISSUE TITLE
Example of defining condition function in recipe

### ISSUE THREAD

**Issue by michaelsorich** [xpepermint/validatablejs#1]
Thanks for adding the condition option to the validation recipe. However, I am not certain how to use it based on the example provided
  condition: () => true, // [optional] a condition which switches the validation on/off

The main issue I have is how to access from within the condition function defined, the current value of other fields in the model. For example if I wished for the field (e.g. phone_number) to only be required when another field (e.g. primary_contact) had a specific value (e.g. 'phone'). When I define the condition function what variables are available or should be passed in to enable evaluating the state of other fields in the document?

let recipe = {
  validator: 'presence', 
  message: 'value must be present', 
  condition: () => { ?.primary_contact == 'phone' }, //?
}; 

Thanks

**Comment by xpepermint** [comment]
I think you are talking about [objectschema](https://github.com/xpepermint/objectschemajs/blob/master/src/documents.ts#L95) package. A model sets a `context` for each validator so you should get Document's context using `this`.

```js
let recipe = {
...
condition () { return this.primaryContact == 'phone' }
};
```

**Comment by michaelsorich** [comment]
Thanks for the example - I can now get what I want to work.

As a followup questions I wish to define a string field which is not required but if it is prenent (non empty) then it needs to match a regex pattern. However, if I use a stringMatch validator (there is no presence validator defined which presumably signals that blank/empty values are allowed) the field is considered invalid when blank (because it does not fit the regular expression defined). One option is to additionally include an empty string value in the regular expression, or perhaps set a condition where the stringMatch is only turned on when the value is not blank - is either of these the approach recommended? I ask because some other validation libraries by default do not evaluate the validation rules defined if it a value is not required and the value is empty - i.e. if a field is not required, then an empty/blank value is automatically valid irrespective of the other validation rules.

Thanks

**Comment by xpepermint** [comment]
This is what you should do:

```js
let recipe = {
  validator: 'stringMatch',
  message: 'value match pattern',
  condition () { return !!this.primaryContact }
};
```

**Comment by xpepermint** [comment]
NOTICE: [Objectschema.js](https://github.com/xpepermint/objectschema) `v4` has been released and the API has changed. The example above should look something like this:
```js
let recipe = {
  validator: 'stringMatch',
  message: 'value match pattern',
  condition () { return !!this.value } // `this` refers to the Field instance
};
```
